### ISSUE TITLE
Build on Windows with Visual Studio 2015

### ISSUE THREAD

**Issue by amarhin** [couchbase/couchbase-lite-java-native#23]
Below a quick fix for building couchbase-lite-java-native on Windows with a fresh Visual Studio 2015 environment.

It seems that vs2015 go along with a SDK refactoring regarding headers and libraries (http://blogs.msdn.com/b/vcblog/archive/2015/03/03/introducing-the-universal-crt.aspx) and Gradle, for now, not handles these changes (https://discuss.gradle.org/t/automatic-detection-of-visual-studio-community-2015-rc-not-working-properly/10309).

For a success build, just add these few lines in the build.gradle :

The default properties for headers (compilee) and libraries (linker) with a standard installation
```
def VS_2015_INCLUDE_DIR = "C:/Program Files (x86)/Windows Kits/10/Include/10.0.10150.0/ucrt"
def VS_2015_LIB_DIR = "C:/Program Files (x86)/Windows Kits/10/Lib/10.0.10150.0/ucrt"
```

The extra compiler and linker options

```
libraries {
    all {
        binaries.all {
            if (targetPlatform.operatingSystem.macOsX) {
                ...
            } else if (targetPlatform.operatingSystem.linux) {
                ...
            } else if (targetPlatform.operatingSystem.windows) {
                ...
                cCompiler.args "-I" + VS_2015_INCLUDE_DIR
                if(targetPlatform.architecture.name == "x86") {
                    linker.args "/LIBPATH:" + VS_2015_LIB_DIR + "/x86"
                }
                else if(targetPlatform.architecture.name == "x86_64" || targetPlatform.architecture.name == "amd64") {
                    linker.args "/LIBPATH:" + VS_2015_LIB_DIR + "/x64"
                }              
            }
        }
    }
}
```

Just run **gradlew.bat clean build** and the build will be successful.

![gradle-vs2015](https://cloud.githubusercontent.com/assets/7602575/9223577/b6eeb14e-40fb-11e5-9e9e-de1c6a183107.png)

**Comment by hideki** [comment]
Hi @amarhin,
Thank you very much for posting solution for VS 2015 issue.
I added link to this from README.
Thanks again!

**Comment by hcoona** [comment]
This could be removed after https://github.com/gradle/gradle/pull/500 closed.
